server:
  port: 18097

spring:
  application:
    name: wisenote-backend-core
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: dev_admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  session:
    store-type: none
  data:
    rest:
      base-path: /api
  jackson:
    default-property-inclusion: NON_NULL

#spring.liquibase.change-log=classpath:db/changelog/db.changelog-local.xml
